USE LibraryDb

CREATE TABLE Contacts
(
Id INT PRIMARY KEY IDENTITY,
Email NVARCHAR(100),
PhoneNumber NVARCHAR(20),
PostAddress NVARCHAR(200),
Website NVARCHAR(50)
)

CREATE TABLE Authors
(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(100) NOT NULL,
ContactID INT FOREIGN KEY REFERENCES Contacts(Id)
)

CREATE TABLE Libraries
(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(50) NOT NULL,
ContactId INT FOREIGN KEY REFERENCES Contacts(Id)
)

CREATE TABLE Genres
(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(30) NOT NULL
)

CREATE TABLE Books 
(
Id INT PRIMARY KEY IDENTITY,
Title NVARCHAR(100) NOT NULL,
YearPublished INT NOT NULL,
ISBN NVARCHAR(13) UNIQUE NOT NULL,
AuthorId INT FOREIGN KEY REFERENCES Authors(Id),
GenreId INT FOREIGN KEY REFERENCES Genres(Id)
)

CREATE TABLE LibrariesBooks
(
LibraryId INT FOREIGN KEY REFERENCES Libraries(Id),
BookId INT FOREIGN KEY REFERENCES Books(Id)
)

